# Generated by Django 5.0.4 on 2024-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
